version: '3.1'

services:
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: super-heros-db
    volumes:
      - ../data:/var/lib/mysql
    ports:
      - 3306:3306
